[pytest]
# Always run with these command-line flags
# -v: verbose, -ra: show extra test summary info, --tb=short: shorter tracebacks
; addopts = -v -ra --tb=short

# Restrict pytest to only look for tests inside these specific directories
testpaths =
    tests

# Custom file, class, and function naming patterns for test discovery
python_files = test_*.py *_test.py
python_classes = Test* *Tests
python_functions = test_*

markers =
    live_api: integration tests for the Overpass API

